sudo: required
language: node_js
node_js:
  - '10'
  - '9'
  - '8'
services:
  - docker

install:
  - npm install

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - sleep 15

script:
  - npm run lint
  - npm run test:ci
  - npm run coverage:upload
